#! /bin/bash

for fp in ./input_files/*.micro
do
    fn="${fp##*/}"

    echo ------------------------------------------------------------------------------------
    echo testing...$fn
	./compiler ./input_files/$fn > test.tiny
    # RUN TEST.tiny
    cat ${fp%.micro}.input | ./tiny test.tiny
    echo =============================sample output==========================================
    cat ${fp%.micro}.input | ./tiny ./output_files/${fn%.micro}.out

    echo ------------------------------------------------------------------------------------
	#output=$(diff -d test.out ./output_files/${fn:14:${#fn}-19}out)

done

rm test.out -rf


